# Generated by Django 5.1.1 on 2024-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tasklist",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID",),),
                ("task", models.CharField(max_length=300)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
    ]
