# Generated by Django 4.2.16 on 2024-10-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist_app", "0002_tasklist_manage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
